name: Intégration continu

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    name: Tests ✅
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 18
      - run: npm run test
